name: InsurgenceKills
version: '${project.version}'
main: com.saturn_dev.insurgencekills.InsurgenceKills
api-version: 1.16
authors: [ SaturnPlugins ]
description: Kills Plugin
website: saturn-dev.com
